version: "3.8"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ZOHO_PASSWORD: ${ZOHO_PASSWORD}
      DEBUG: ${DEBUG}
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade &&
             gunicorn --bind 0.0.0.0:5000 wsgi:application"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./frontend:/app
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  postgres_data:
